### ISSUE TITLE
functions doesn't work on kibana 4.5.0 and 4.5.1

### ISSUE THREAD

**Issue by y0uzha** [nbs-system/mapster#8]
hi. i'm trying to using this plugin on kibana 4.5.0 and 4.5.1 but it doesn't work normally on it. all the functions doesn't work. for example : 2d map, timestamp, target location, etc. it only shows 3d maps and there are no any arrows showed event i've set the geohash field.

is there any config that i've missed? pls advice

![screenshot from 2017-07-19 13 35 58](https://user-images.githubusercontent.com/7866726/28353742-4f8920b6-6c87-11e7-9fcb-e28998dc3a6b.png)

**Comment by xarkes** [comment]
Hi,
This should be working on 4.5.1 as well as on 4.5.0. Are you sure you read the Readme correctly ? The aggregations order and types are strict. If you want a 2D map you have to (un)check it into the parameters panel (right of the Data panel as you can see on your screenshot).

**Comment by xarkes** [comment]
Also note that the multiple target location might be broken, so try with a single target first, and let me know about it. Another usefull thing would be to print the javascript logs of your browser, there might be some warnings and error there.

**Comment by y0uzha** [comment]
Hi,

i've uncheck **use a 3d map** and apply changes but it still show 3d map on there and i've got some error message on my js logs like pictures below

![screenshot from 2017-07-19 14 14 44](https://user-images.githubusercontent.com/7866726/28355351-cd4df8b8-6c8d-11e7-96a7-ff7305b6b32f.png)

![screenshot from 2017-07-19 14 19 48](https://user-images.githubusercontent.com/7866726/28355376-e49ea5d0-6c8d-11e7-9a02-fe8c82f1a809.png)

**Comment by xarkes** [comment]
I think you have to refresh for the effects to take place. Also as you can see, you forgot one required aggregation, this is the one which is going to set the type and color of your event. After setting it and refreshing with F5 everything should be fine.

**Comment by y0uzha** [comment]
i have try to refresh with f5 and now i've got the blank white map.
i've got an error renderer message like below. this error only showed when i try to renderer 2d map.

![screenshot from 2017-07-19 14 45 24](https://user-images.githubusercontent.com/7866726/28356144-26331f5a-6c91-11e7-8c93-673b08c72e6f.png)

**Comment by xarkes** [comment]
Yes there was a small issue, try again with the latest commit

**Comment by y0uzha** [comment]
The error renderer still shows with the latest commit. and now there is another error too with it.
![screenshot from 2017-07-19 15 52 39](https://user-images.githubusercontent.com/7866726/28358810-7086684c-6c9a-11e7-8707-eda49c3210bb.png)

**Comment by y0uzha** [comment]
sorry, 
i think the two errors below renderer error just because target location is not set. 
so i try to set the target location and then i found a new one error message.

![screenshot from 2017-07-19 15 58 20](https://user-images.githubusercontent.com/7866726/28359095-596280dc-6c9b-11e7-9092-5491b069d6cf.png)

**Comment by xarkes** [comment]
Ok sorry I did some refactoring, now it should be working fine !

**Comment by y0uzha** [comment]
so sorry but the error still same like before 

![screenshot from 2017-07-19 16 44 30](https://user-images.githubusercontent.com/7866726/28361078-b9b56f48-6ca1-11e7-876b-c105221616e0.png)

i think the **geohash.toLowerCase** error caused by target location parameter. that error appear only when i use target location parameter. even i'm using 3d map

**Comment by xarkes** [comment]
Hmm have you tried restarting Kibana ? There might be some code cached which is why it cannot find the render function (which was not declared before).
About the toLowerCase error I don't know where it comes from, it is used by some libraries, maybe their API changed and they might need an update. But try first restarting Kibana so there's no old Mapster version cached.

**Comment by y0uzha** [comment]
yap i've already restart kibana before. i'm sure there is no cached anymore. i'm using the private window too on my browser but it still error like before

**Comment by xarkes** [comment]
I'm sorry but I cannot test on my computer now.
Can you try with commit 0493ef24187cdb86c5b8a973029edd439cb81fef ?

**Comment by xarkes** [comment]
But are you sure you followed the instructions in the README ?

```bash
rm -r optimize/bundles
./bin/kibana
```

**Comment by y0uzha** [comment]
ah you're right. 
i'm really sorry for my mistakes. 
i forgot to delete the _bundles_ directory after i clone the new commit. 
now the 2d maps has been successfully rendered.

thank you so much for your help.

**Comment by xarkes** [comment]
You're welcome.
